<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXnaxh3Q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXnaxh3Q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXnaxh3Q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXnaxh3Q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXnaxh3Q\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xnaxh3Q',
    'container.build_id' => '58760ca3',
    'container.build_time' => 1689665687,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXnaxh3Q');
