<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'https://localhost:8080/build/runtime.js',
                'https://localhost:8080/build/vendors~_tmp_copy~app~products.js',
                'https://localhost:8080/build/vendors~app~products.js',
                'https://localhost:8080/build/vendors~app.js',
                'https://localhost:8080/build/app.js',
            ],
        ],
        'products' => [
            'js' => [
                'https://localhost:8080/build/runtime.js',
                'https://localhost:8080/build/vendors~_tmp_copy~app~products.js',
                'https://localhost:8080/build/vendors~app~products.js',
                'https://localhost:8080/build/vendors~products.js',
                'https://localhost:8080/build/products.js',
            ],
        ],
    ],
],

]];
